"""Added pulse system

Revision ID: 19d0dce5626
Revises: 2f28e7704f7
Create Date: 2015-03-27 11:33:08.858948

"""

# revision identifiers, used by Alembic.
revision = '19d0dce5626'
down_revision = '2f28e7704f7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pulse',
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('violence', sa.Float(), nullable=True),
    sa.Column('river', sa.Float(), nullable=True),
    sa.Column('teleport', sa.Float(), nullable=True),
    sa.Column('nature', sa.Float(), nullable=True),
    sa.Column('mobile', sa.Float(), nullable=True),
    sa.Column('sound', sa.Float(), nullable=True),
    sa.Column('zone', sa.Float(), nullable=True),
    sa.Column('update', sa.Float(), nullable=True),
    sa.Column('variation', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('width')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pulse')
    ### end Alembic commands ###
