"""Option hotboot column

Revision ID: 4704324ad05
Revises: 19d0dce5626
Create Date: 2015-09-16 06:36:49.382082

"""

# revision identifiers, used by Alembic.
revision = '4704324ad05'
down_revision = '19d0dce5626'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option', sa.Column('hotboot', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('option', 'hotboot')
    ### end Alembic commands ###
